
FROM mysql:8.0.29

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=todo_list
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

COPY ./scripts/ /docker-entrypoint-initdb.d/

# Path: backend/scripts/

# crie um código Dockerfile para o MySQL que cria um banco de dados chamado todo_list e um usuário chamado root com a senha root.































